#ifndef FREYALAUNCHTESTA_GLOBAL_H
#define FREYALAUNCHTESTA_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(FREYALAUNCHTESTA_LIBRARY)
#  define FREYALAUNCHTESTASHARED_EXPORT Q_DECL_EXPORT
#else
#  define FREYALAUNCHTESTASHARED_EXPORT Q_DECL_IMPORT
#endif

#define FRYTA_CMD_TEST_1            0x0000000100000088
#define FRYTA_CMD_TEST_2            0x0000000200000088

#endif // FREYALAUNCHTESTA_GLOBAL_H
