#ifndef FREYALAUNCHTESTB_GLOBAL_H
#define FREYALAUNCHTESTB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(FREYALAUNCHTESTB_LIBRARY)
#  define FREYALAUNCHTESTBSHARED_EXPORT Q_DECL_EXPORT
#else
#  define FREYALAUNCHTESTBSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // FREYALAUNCHTESTB_GLOBAL_H
